efix now removes unnecessary leading lines in javadoc.
I'm still working on the trailing lines.

diff --git a/.local/bin/efix b/.local/bin/efix
--- a/.local/bin/efix
+++ b/.local/bin/efix
@@ -181,3 +181,23 @@ if efix_init 'scanning file encodings' file iconv; then
 	done
 fi
 
+
+# UNNECESSARY EMPTY LINES IN JAVADOC COMMENTS ----------------------------------
+
+if efix_init 'fixing unnecessary empty lines in javadoc' ex; then
+	for f in $files; do
+		# leading lines:
+		sed -n '1h;1!H;${g;s/\/\*\*\n\([ ]*\*\n\)*/\/\*\*\n/g;p}' \
+				"$f" >"$TMPFILE"
+		[ $? -eq 0 ] || { printf "\033[31merror [ex]\033[0m\n" 1>&2; continue; }
+		mv -f "$TMPFILE" "$f"
+		[ $? -eq 0 ] || { printf "\033[31merror [mv]\033[0m\n" 1>&2; continue; }
+
+		# trailing lines:
+		# TODO
+		#printf "%%s/%s/%s/g\nw\nq\n" '\([ ]*\)\*\/\n' '\1\*\/\r' #| \
+				#ex -s "$f" 1>/dev/null || \
+				#{ printf "\033[31merror [ex]\033[0m\n" 1>&2; break; }
+	done
+fi
+
