Rename screen calibration colour profiles, sanitise adjustment script.
No longer named after hostname, but after screen that is primarly used
by them (ixh => thinkpad, phobia => crappy asus screens).

diff --git a/.local/bin/lcdadjust b/.local/bin/lcdadjust
--- a/.local/bin/lcdadjust
+++ b/.local/bin/lcdadjust
@@ -1,38 +1,24 @@
-#!/bin/bash
+#!/bin/sh
 
-lcdadjust_start() {
-	if [ -e ~/.config/argyll/$HOSTNAME.icc ]; then
-		for ((i=1; i<=$(dynenv NUM_SCREENS); i++)); do
-			dispwin -d $i $XDG_CONFIG_HOME/argyll/$HOSTNAME.icc
-		done
-	fi
-}
-
-lcdadjust_stop() {
-	for ((i=1; i<=$(dynenv NUM_SCREENS); i++)); do
-		true # TODO find out how to disable a display calibration
-	done
-}
-
-lcdadjust_help() {
-	printf "%s start|restart|stop\n" $(basename $0)
-}
-
-command="$1"
-shift
-
-case "$command" in
-	start)
-		lcdadjust_start;;
-
-	stop)
-		lcdadjust_stop;;
-
-	restart)
-		lcdadjust_stop
-		lcdadjust_start;;
-
-	*)
-		lcdadjust_help
+ICC_PROFILE=''   # initial profile is undefined
+case "$HOSTNAME" in
+	ixh)    ICC_PROFILE=lenovo_thinkpad_x230 ;;
+	phobia) ICC_PROFILE=phobia phobia ;;
 esac
+if [ -z "$ICC_PROFILE" ]; then
+	echo "no colour profile defined for $HOSTNAME" >&2
+	exit 1
+fi
+i=1
+for p in $ICC_PROFILE; do
+	ICC_PATH="$XDG_CONFIG_HOME"/argyll/${p}.icc
+	if [ ! -f "$ICC_PATH" ]; then
+		echo "file not found: $ICC_PATH" >&2
+		continue
+	fi
+	dispwin -d $i "$ICC_PATH"
+	i=$(($i+1))
+	unset ICC_PATH
+done
+unset ICC_PROFILE
 
