[vls] Handle shutdown gracefully
Given that the service file calls ExecStop whenever the process stops on
its own, we need to handle that case, otherwise it will translate to a
failed state, even if everything went correctly.

We let the service file call 'vls stop', which handles the case of no
process running gracefully. Hence the return to 'start' and 'stop'
commands in the script.

diff --git a/.local/src/vls/vls/vls b/.local/src/vls/vls/vls
--- a/.local/src/vls/vls/vls
+++ b/.local/src/vls/vls/vls
@@ -8,79 +8,113 @@ vls_die() {
 	exit 1
 }
 
-vls_term() {
-	echo 'Received SIGINT, shutting down VLS ...'
-	if [ -e $sockfile ]; then
-		test -n "$(which -a socat)" || vls_die "socat: command not found"
+vls_check_root() {
+	test $(id -u) -eq 0 || vls_die "$0 requires you to be root"
+}
+
+vls_help() {
+	vls_die "Usage: $0 start|stop"
+}
+
+vls_pre_stop() {
+	interrupted=1
+}
+
+vls_start() {
+	# default VM MAC address:
+	vls_mac='52:54:00:12:34:56'
+
+	# dnsmasq config:
+	echo "Getting dnsmasq configuration ..."
+	dnsmasq_conf='/etc/dnsmasq.conf'
+	if [ ! -e $dnsmasq_conf ]; then
+		echo "$dnsmasq_conf not found, using default MAC address" >&2
+	else
+		vls_mac_tmp="$(grep '^dhcp-host=' "$dnsmasq_conf" | head -n 1 | \
+		               sed -e 's/^dhcp-host=//g' | cut -d ',' -f 1)"
+		vls_mac="$vls_mac_tmp"
+	fi
+
+	# RAID devices:
+	echo "Checking devices for RAID setup ..."
+	partdev=/dev/sda6                         # TODO config file or command line
+	mbrfile=/var/lib/vls/mbr                  # TODO config file or command line
+	raiddev=/dev/md0                          # TODO config file or command line
+	test -e $partdev || vls_die "System partition $partdev not found"
+	test -e $mbrfile || vls_die "MBR file $mbrfile not found"
+	test -e $raiddev && vls_die "$raiddev already exists"
+
+	# catch interrupts:
+	trap vls_pre_stop SIGINT
+	trap vls_pre_stop SIGTERM
+	trap vls_pre_stop SIGHUP
+
+	# build RAID device:
+	echo "Building RAID device ..."
+	loopdev=$(losetup -f)
+	test -n "$loopdev" || vls_die "No free loop device"
+	losetup $loopdev $mbrfile || vls_die "losetup failed"
+	mdadm --build --verbose $raiddev \
+	      --level=linear --raid-devices=2 $loopdev $partdev
+	if [ $? -ne 0 ]; then
+		losetup -d $loopdev
+		vls_die "mdadm failed"
+	fi
+
+	# build runtime files:
+	echo "Creating runtime directory ..."
+	mkdir -p $runpath
+
+	# launch VM if not interrupted:
+	if [ $interrupted -eq 1 ]; then
+		echo 'Received shutdown signal, not starting VLS'
+	else
+		echo "Launching VLS ..."
+		qemu-system-x86_64 -enable-kvm -cpu host -smp 4 \
+		                   -m 4096 \
+		                   -drive file=$raiddev \
+		                   -net nic,model=virtio,macaddr=$vls_mac -net vde \
+		                   -nographic -vnc :7 \
+		                   -monitor unix:$sockfile,server,nowait &
+		qemu_pid=$!
+		echo "qemu_pid=$qemu_pid" > $lockfile
+		trap vls_stop SIGINT
+		trap vls_stop SIGTERM
+		trap vls_stop SIGHUP
+		wait $qemu_pid
+	fi
+
+	# nuke socket:
+	echo "Nuking runtime files ..."
+	rm -rf $runpath
+
+	# nuke RAID device:
+	echo "Nuking RAID device ..."
+	mdadm --stop $raiddev
+	losetup -d $loopdev
+}
+
+vls_stop() {
+	echo 'Stopping the VLS ...'
+	if [ -e $sockfile ] && [ -n "$(which -a socat)" ]; then
 		echo 'system_powerdown' | socat stdio UNIX-CONNECT:$sockfile
+	elif [ -e $lockfile ]; then
+		echo 'socat: command not found, killing machine'
+		. $lockfile
+		kill $qemu_pid
+	else
+		echo 'VLS does not seem to be running, doing nothing'
 	fi
 }
 
-# check permission:
-test $(id -u) -eq 0 || vls_die "$0 requires you to be root"
-
-# default VM MAC address:
-vls_mac='52:54:00:12:34:56'
-
-# dnsmasq config:
-echo "Getting dnsmasq configuration ..."
-dnsmasq_conf='/etc/dnsmasq.conf'
-if [ ! -e $dnsmasq_conf ]; then
-	echo "$dnsmasq_conf not found, using default MAC address" >&2
-else
-	vls_mac_tmp="$(grep '^dhcp-host=' "$dnsmasq_conf" | head -n 1 | \
-				   sed -e 's/^dhcp-host=//g' | cut -d ',' -f 1)"
-	vls_mac="$vls_mac_tmp"
-fi
-
-# RAID devices:
-echo "Checking devices for RAID setup ..."
-partdev=/dev/sda6                             # TODO config file or command line
-mbrfile=/var/lib/vls/mbr                      # TODO config file or command line
-raiddev=/dev/md0                              # TODO config file or command line
-test -e $partdev || vls_die "System partition $partdev not found"
-test -e $mbrfile || vls_die "MBR file $mbrfile not found"
-test -e $raiddev && vls_die "$raiddev already exists"
-
-# build RAID device:
-echo "Building RAID device ..."
-loopdev=$(losetup -f)
-test -n "$loopdev" || vls_die "No free loop device"
-losetup $loopdev $mbrfile || vls_die "losetup failed"
-mdadm --build --verbose $raiddev \
-	  --level=linear --raid-devices=2 $loopdev $partdev
-if [ $? -ne 0 ]; then
-	losetup -d $loopdev
-	vls_die "mdadm failed"
-fi
-
-# runtime folder:
-echo "Creating runtime directory ..."
+# runtime:
 runpath=/run/vls
+lockfile=$runpath/vls.lock
 sockfile=$runpath/vls.sock
-mkdir -p $runpath
+interrupted=0
 
-# trap INT signal (^C):
-trap vls_term SIGINT
-
-# launch VM:
-echo "Launching VLS ..."
-qemu-system-x86_64 -enable-kvm -cpu host -smp 4 \
-				   -m 4096 \
-				   -drive file=$raiddev \
-				   -net nic,model=virtio,macaddr=$vls_mac -net vde \
-				   -nographic -vnc :7 \
-				   -monitor unix:$sockfile,server,nowait      # TODO config file
-pid=$(pgrep qemu-system-x84_64 | grep ${raiddev} | head -n 1)
-
-# nuke socket:
-echo "Nuking runtime files ..."
-rm -rf $runpath
-
-# nuke RAID device:
-echo "Nuking RAID device ..."
-mdadm --stop $raiddev
-losetup -d $loopdev
-
-# Success!
-true
+case "$1" in
+	start) vls_check_root && vls_start ;;
+	stop) vls_check_root && vls_stop ;;
+	*) vls_help ;;
+esac
